RSE-184: Change menu urls
compucorp/uk.co.compucorp.civicrm.prospect pull request #22
Opened 2019-07-16 11:42 UTC by deb1990

2019-07-17 08:45 UTC, tunbola requested changes

2019-07-17 08:45 UTC, tunbola commented on CRM/Prospect/Setup/CreateProspectMenus.php
> +        'url' => 'civicrm/case/add?category=prospecting',
@deb1990 , Can we change this to `civicrm/case/add?category=prospecting&action=add&reset=1`
Adding the reset=1 helps clear the smarty cache for the form so it does not carry values over from it's prior invocation. I see so many references to the action parameter in the Case form BAO too so I think it's a good idea to add that.

2019-07-17 10:26 UTC, tunbola approved these changes

2019-07-18 11:04 UTC, reneolivo approved these changes

2019-07-18 11:05 UTC, reneolivo approved these changes

2019-07-18 11:55 UTC, merged